# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk (for GitVersion)'
    inputs:
      packageType: sdk
      version: 5.x

  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.6.0'

  - task: gitversion/execute@0
    inputs:
      useConfigFile: true
      configFilePath: '$(Build.SourcesDirectory)/GitVersion.yml'

  - task: Npm@1
    displayName: 'Version Stamp'
    inputs:
      command: 'custom'
      customCommand: 'run version-stamp $(Build.BuildNumber)'

  - script: |
      npm run build
    displayName: 'NPM Build'

  - script: |
      npm run test
    displayName: 'Running Tests'

  - task: PublishTestResults@2
    displayName: 'Publishing Tests'
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '**/*-test-result.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: Jasmine Tests
